services:
  - type: web
    name: facebook-share-booster
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0 --server.enableCORS=false
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0